// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"fmt"
)

// Injectors from coffee.go:

func InitializeCoffee() Order {
	coffee := NewCoffee()
	order := NewOrder(coffee)
	return order
}

// coffee.go:

type Coffee struct {
	Name     string
	Quantity int8
	Owner    string
}

type Order struct {
	Coffee Coffee
	Waiter string
}

func NewCoffee() Coffee {
	return Coffee{
		Name:     "Caffuchino",
		Quantity: 1,
		Owner:    "John",
	}
}

func NewOrder(coffee Coffee) Order {
	return Order{
		Coffee: coffee,
		Waiter: "Doe",
	}
}

func (order Order) Ordering() {
	fmt.Printf("%v ordering %v to %v", order.Coffee.Owner, order.Coffee.Name, order.Waiter)
}
