// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"database/sql"
	"time"
)

type CvznCertification struct {
	ID                       string         `json:"id"`
	UserEmail                string         `json:"user_email"`
	CertificateName          sql.NullString `json:"certificate_name"`
	Publisher                sql.NullString `json:"publisher"`
	Issued                   sql.NullString `json:"issued"`
	CertificationDescription sql.NullString `json:"certification_description"`
}

type CvznExpertise struct {
	ID        string         `json:"id"`
	UserEmail string         `json:"user_email"`
	SkillName sql.NullString `json:"skill_name"`
}

type CvznHistoryEducation struct {
	ID               string         `json:"id"`
	EmailUser        string         `json:"email_user"`
	AgencyName       sql.NullString `json:"agency_name"`
	Major            sql.NullString `json:"major"`
	StartDate        sql.NullString `json:"start_date"`
	DateOfCompletion sql.NullString `json:"date_of_completion"`
	Description      sql.NullString `json:"description"`
}

type CvznHobby struct {
	ID                string         `json:"id"`
	CvzPersonalDataID string         `json:"cvz_personal_data_id"`
	HobbyName         sql.NullString `json:"hobby_name"`
}

type CvznOrganization struct {
	ID                      string         `json:"id"`
	UserEmail               string         `json:"user_email"`
	OrganizationName        sql.NullString `json:"organization_name"`
	PositionName            sql.NullString `json:"position_name"`
	StartDate               sql.NullString `json:"start_date"`
	DateOfCompletion        sql.NullString `json:"date_of_completion"`
	OrganizationDescription sql.NullString `json:"organization_description"`
}

type CvznPersonalDatum struct {
	ID                string         `json:"id"`
	EmailUser         string         `json:"email_user"`
	FullName          sql.NullString `json:"full_name"`
	MobilePhoneNumber sql.NullString `json:"mobile_phone_number"`
	DateOfBirth       sql.NullString `json:"date_of_birth"`
	ImageUrl          sql.NullString `json:"image_url"`
	Address           sql.NullString `json:"address"`
	Website           sql.NullString `json:"website"`
	Linkedln          sql.NullString `json:"linkedln"`
	Instagram         sql.NullString `json:"instagram"`
	Facebook          sql.NullString `json:"facebook"`
	AboutMe           sql.NullString `json:"about_me"`
}

type CvznUser struct {
	Email     string    `json:"email"`
	CreatedAt time.Time `json:"created_at"`
}

type CvznWorkExperience struct {
	ID               string         `json:"id"`
	EmailUser        string         `json:"email_user"`
	Position         sql.NullString `json:"position"`
	CompanyName      sql.NullString `json:"company_name"`
	Address          sql.NullString `json:"address"`
	StartDate        sql.NullString `json:"start_date"`
	DateOfCompletion sql.NullString `json:"date_of_completion"`
	JobType          sql.NullString `json:"job_type"`
	Description      sql.NullString `json:"description"`
}
